[WIP] 2020 angular tutorial
workshops-de/angular.de pull request #80
Opened 2020-10-24 09:56 UTC by robinboehm

Update unseres Angular Tutorials auf die neuste Version.

- Mehr Interaktion
- Einfachere Beispiele
- Mehr Bilder
- Kürzer
- Besser
- Schöner
- Toller

Todos:
- [ ] Text: Schleifen mit *ngFor
- [ ] Text: Der erste Service
- [ ] Daten via Rest-API laden
- [ ] Fazit
- [ ] Classroom Tasks erstellen
- [ ] Classroom Tasks erstellen
- [ ] Inhaltiches Review
- [ ] Sprachliches Review

2020-10-24 14:11 UTC, GregOnNet requested changes
Wenn der Artikel steht, sollten wir languagetool.org bemühen, um die Grammatik zu korrigieren.

2020-10-24 14:11 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +<app-info-box></app-info-box>
```suggestion
<!-- app.component.html> 
<app-info-box></app-info-box>
```

Für Leute, die den Text nach Snippets scannen, ist es hilfreich in den Code-Snippets die Dateinamen im Kommentar zu nennen.
Damit können die Snippets schnell zugeordnet werden.

2020-10-24 14:11 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +Wenn ihr nun eure Anwendung wieder im Browser öffnet solltet ihr die Ausgabe `info-box works!` sehen.
```suggestion
Wenn ihr nun eure Anwendung wieder im Browser öffnet, solltet ihr die Ausgabe `info-box works!` sehen.
```

2020-10-24 14:11 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +Ein historischer Moment, nehmt euch ein paar Sekunden eure erste eigene Komponente zu bewundern. 😉
😆 Captain Motivation. 👍

2020-10-24 14:11 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +Eine rein statische Komponente ist natürlich nur sehr begrenzt in einer Anwendung nutzbar.
```suggestion
Eine Komponente mit statischen Inhalten ist natürlich nur sehr begrenzt in einer Anwendung nutzbar.
```

... um eine Konfusion mit statischen Klassen zu vermeiden.

2020-10-24 14:11 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +
Hier fehlt mir ein einleitender Abschnitt.
Ich würde jetzt eine Überleitung von der Info-Box zu den Büchern erwarten...
... Moment, sprechen wir oben nicht von Todos? 🤔 

Mehr als 2 Baustellen würde ich hier nicht aufmachen.
InfoBox und Books reicht vollkommen.

2020-10-24 14:11 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +### Dependency Injection
Ok, jetzt verstehe ich.
Der Artikel scheint noch in der Fertigung zu sein... :-D

2020-10-24 14:11 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +getBooks(): [] {
Wenn Typisierung hier gemacht wird, sollten Interfaces zunächst eingeführt werden.
Dann kann hier `Book[]` zurückgegeben werden.

2020-10-24 14:41 UTC, robinboehm commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +Ein historischer Moment, nehmt euch ein paar Sekunden eure erste eigene Komponente zu bewundern. 😉
😎

2020-10-24 14:42 UTC, robinboehm commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +Es ist  nicht erforderlich das AngularJS(Angular 1) Tutorial vorher durchzuarbeiten. Diese Einführung ist für Anfänger gedacht, die gerade mit Angular beginnen. Das Beispiel orientiert sich an den er
Halte ich für irrelevant um Angular 2+ zu verstehen.

2020-10-24 14:43 UTC, robinboehm commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +getBooks(): [] {
Hatte ich erst drin, habe es dann raus genommen um den Fokus eher auf die Features von Angular zu legen.
Welchen Vorteil hat der Leser wenn er die Grundlagen von Angular verstehen will und hier Interfaces nutzt?
Ich find es "richtig" und "komplett", aber auch wichtig wenn jemand grad den erste Eindruck bekommen will?

2020-10-24 14:46 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +getBooks(): [] {
Es gehen beide Wege,
Aber einen Mix würde ich nicht machen.

Wenn Typisierung keine Rolle spielen soll, dann sollte `: []` entfernt werden. -> Noch mehr Fokus. :)

2020-10-24 14:47 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +Es ist  nicht erforderlich das AngularJS(Angular 1) Tutorial vorher durchzuarbeiten. Diese Einführung ist für Anfänger gedacht, die gerade mit Angular beginnen. Das Beispiel orientiert sich an den er
Hätte es auch eher als Bonus-Info in einen eigenem Kasten gesehen.
Muss aber nicht rein. 👍

2020-10-24 14:53 UTC, robinboehm commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +getBooks(): [] {
Haha, das ist ein guter Punkt! Danke!

2020-10-25 09:06 UTC, robinboehm commented
Sprachlich werde ich mit Justus aus unserem Team das am Ende nochmal checken. Er ist unser Text-Profi und hat Deutsch und Englisch studiert =)

2020-10-26 14:56 UTC, GregOnNet requested changes

2020-10-26 14:56 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +}
Hier ist eine Klammer zu viel.

2020-10-26 14:56 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +Angular ist in vielerlei Hinsicht sehr opinionated(meinungsstark). Dies bedeutet, dass viele Entscheidungen über Architektur und Rendering dem/der Entwickler:in bereits abgenommen werden. Dies hat na
```suggestion
Angular ist in vielerlei Hinsicht sehr opinionated(meinungsstark). Das bedeutet, dass viele Entscheidungen über Architektur und Rendering dem/der Entwickler:in bereits abgenommen werden. Dies hat natürlich den Vorteil, dass sich das Projektteam 100% auf die Umsetzung von Features konzentrieren kann und nicht die grundlegende Architektur eigenständig aufbauen muss.
```

2020-10-26 14:56 UTC, GregOnNet commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +Wenn Ihr euch weiter mit uns und anderen Austauschen wollt, kommt in unseren [Slack Chat](/slack) mit über 2000 wunderbaren anderen Menschen! Zusammen lernt sich besser! :)
```suggestion
Wenn Ihr euch weiter mit uns und anderen austauschen wollt, kommt in unseren [Slack Chat](/slack) mit über 2000 wunderbaren anderen Menschen! Zusammen lernt sich besser! :)
```

2020-10-27 11:59 UTC, robinboehm commented on _posts/2020-10-19-angular-tutorial-deutsch/2020-10-19-angular-tutorial-deutsch.md
> +}
Check ich nicht. Bin blind. Bitte genauer :D

2021-05-27 09:31 UTC, closed without merging